# Generated by Django 5.1.2 on 2024-11-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0002_rename_usermessages_id_message_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='UserMessages_id',
        ),
    ]
